name: unit tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  required_unit_tests:
    name: Build and Run Go Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install SDL2 and OpenGL Dependencies
      run: |
        sudo apt-get update
        # SDL2
        sudo apt-get install -y libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-net-dev
        # OpenGL
        sudo apt-get install -y mesa-utils libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev
# golangci-lint run --fix

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          /var/cache/apt/archives
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-deps-${{ hashFiles('**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-deps-

    # engine

    - name: Run /engine golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: engine
        args: --timeout=5m
      timeout-minutes: 5

    - name: Run /engine tests
      run: go test ./...
      working-directory: engine

    # core

    - name: Run /core tests
      run: go test ./...
      working-directory: core

    - name: Run /core golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: engine
        args: --timeout=5m
      timeout-minutes: 5
