name: unit tests

on:
  pull_request:
    branches:
      - main

jobs:
  required_unit_tests:
    name: Build and Run Go Tests
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Download core Go Modules
      run: go mod download
      working-directory: core

    - name: Download engine Go Modules
      run: go mod download
      working-directory: engine

    - name: run engine tests
      run: go test ./...
      working-directory: engine

    - name: run core tests
      run: go test ./...
      working-directory: core

    - name: Static Analysis (Go Vet)
      run: go vet ./...
