name: unit tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  required_unit_tests:
    name: Build and Run Go Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install SDL2 and OpenGL Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev
        sudo apt-get install -y libgl1-mesa-dev xorg-dev

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: run engine tests
      run: go test ./...
      working-directory: engine

    - name: run core tests
      run: go test ./...
      working-directory: core

    - name: Static Analysis (Go Vet)
      run: go vet ./...
